name: Deploy to Release Repo
# Builds, tests, and publishes dev builds of Android SDKs. The CD destination and CI configuration are handled by your gradle files. You only invoke tasks here
# ** Building multiple modules? If one depends on another, you'll have to build the dependencies in one step and the rest in another. 
#      See below for more info 
# REPOSITORY SECRETS REQUIRED: (see https://docs.github.com/en/actions/security-guides/encrypted-secrets) 
#   "ARTIFACTORY_EMAIL": an artifactory account email with publish permissions for the destination artifactory
#   "ARTIFACTORY_PASSWORD": the password for the artifactory account

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      # This step will build all modules configured for publication and publish them
      # Does your project publish multiple libraries in a dependency chain? You'll have to add another copy of this step and build the dependency in the first one
      - name: Deploy to Release Repo
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: artifactoryPublish
        env:
          ORG_GRADLE_PROJECT_artifactory_user: ${{ secrets.ARTIFACTORY_EMAIL }}
          ORG_GRADLE_PROJECT_artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
